name: ESP32 CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build ESP32 Firmware
        run: platformio run -e freenove_esp32_s3_wroom

      - name: Run Native Unit Tests
        run: platformio test -e native